pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            steps {
                agent {
                    docker {
                        image 'golang:1.20'
                        //args '-v /go/pkg/mod:/go/pkg/mod'
                        reuseNode true
                    }
                }
                dir('bugtracker-backend') {
                    //go test -v ./...
                    sh 'go test -v ./...'
            }
        }
    }
}
